function generateIndex (totalComp, indexNm, compPerPage)

if ~isa (totalComp, 'numeric') || mod (totalComp, 1) ~= 0
    error ('generateIndex: the first input, totalComp, is not integer');
end
if exist (strcat (indexNm, '1.html'), 'file')
    error ('generateIndex: the target file exist!');
end

[~, filenm] = fileparts (indexNm);

numPages = ceil (totalComp/compPerPage);

for page = 1:numPages

% generate index page
fid = fopen (strcat (indexNm, num2str(page), '.html'), 'w');
fprintf (fid, '<html>\n');
fprintf (fid, '<head>\n');
fprintf (fid, '\t<title>gRAICAR Report: Index (page %d of %d)</title>\n', page, numPages);
fprintf (fid, '</head>\n');
fprintf (fid, '<body>\n');
fprintf (fid, '\t<h1 align="center">gRAICAR Report (page %d of %d)</h1>\n', page, numPages);
% make page links if there are more than one page
if numPages ~= 1
    fprintf (fid, '\t<h2 align="center">');
    for p = 1:numPages
        fprintf (fid, '<a href="%s">%d</a>	', strcat (filenm, num2str(p), '.html'), p);
    end
    fprintf (fid, '</h2>\n');
end

fprintf (fid, '<hr>\n<br><br>\n'); 

fprintf (fid, '<table border="0" cellpadding="0">\n');
fprintf (fid, '<caption><h2>Overall Statistics</h2></caption>\n');
fprintf (fid, '\t<tr><td>&nbsp;&nbsp;</td></tr>\n');
fprintf (fid, '\t<tr>\n');
fprintf (fid, '\t\t<th align="center">Rank of mean inter-subject similarity</th>\n');
fprintf (fid, '\t\t<th align="center">Ratio of significant subjects</th>\n');
fprintf (fid, '\t<tr>\n');
fprintf (fid, '\t\t<td><img src="rank_meanSim.png" align="left" width="417" height="312" border="0"></td>\n');
fprintf	(fid, '\t\t<td><img src="rank_betaRank.png" align="left" width="417" height="312" border="0"></td>\n');
fprintf (fid, '\t</tr>\n');
fprintf (fid, '</table>\n');
fprintf (fid, '<br><br>\n<hr>\n<br><br>\n');


for compInd = 1:min (compPerPage, totalComp-compPerPage*(page-1))
comp = (page-1)*compPerPage+compInd;
% table and caption
fprintf (fid, '\t<br><br>\n');
fprintf (fid, '\t<table border="0" cellpadding="0">\n');
fprintf (fid, '\t<caption><h2>Aligned Component %d</h2></caption>\n', comp);

% leave some space
fprintf (fid, '\t\t<tr>\n');
fprintf (fid, '\t\t\t<td>&nbsp;</td>\n');
fprintf (fid, '\t\t</tr>\n');

% show AC map
fn = sprintf ('map_AC%d.png', comp);
fn2 = sprintf ('map_AC_nothresh%d.png', comp);
fprintf (fid, '\t\t<tr>\n');
fprintf (fid, '\t\t\t<td align="left" colspan="3"><a href="%s"><img src="%s" width="834" height="500" border="0"></a></td></td>\n', fn2, fn);
fprintf (fid, '\t\t</tr>\n');

% leave some space
fprintf (fid, '\t\t<tr>\n');
fprintf (fid, '\t\t\t<td>&nbsp;</td>\n');
fprintf (fid, '\t\t</tr>\n');

% header for the 2nd row
fprintf (fid, '\t\t<tr>\n');
fprintf (fid, '\t\t\t<th>Inter-subject similarity matrix</th>\n');
fprintf (fid, '\t\t\t<th>Subject load</th>\n');
fprintf (fid, '\t\t\t<th>Confidence of subject load</th>\n');
fprintf (fid, '\t\t</tr>\n');
	
% show 3 figures in the 2nd row
fprintf (fid, '\t\t<tr>\n');
fn = sprintf ('simMtx_AC%d.png', comp);
fprintf (fid, '\t\t\t<td><img src="%s" align="left" width="334" height="250" border="0"></td>\n', fn);
fn = sprintf ('subjLoad_AC%d.png', comp);
fprintf (fid, '\t\t\t<td><img src="%s" align="left" width="250" height="250" border="0"></td>\n', fn);
fn = sprintf ('sig_subjLoad_AC%d.png', comp);
fprintf (fid, '\t\t\t<td><img src="%s" align="left" width="250" height="250" border="0"></td>\n', fn);
fprintf (fid, '\t\t</tr>\n');

fprintf (fid, '\t</table>\n');
fprintf (fid, '\t<br><br>\n');
fprintf (fid, '\t<hr>\n');
end

% links for mulitple pages again
if numPages ~= 1
    fprintf (fid, '\t</br></br>\n');
    fprintf (fid, '\t<h2 align="center">');
    for p = 1:numPages
        fprintf (fid, '<a href="%s">%d</a>	', strcat (filenm, num2str(p), '.html'), p);
    end
    fprintf (fid, '</h2>\n');
end
    
fprintf (fid, '\t<h3 align="center">Automatically Generated by gRAICAR</h3>\n');
fprintf (fid, '</body>\n');
fprintf (fid, '</html>\n');
fclose (fid);
end